name: Generate Contribution Grid Snake

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite UTC
  workflow_dispatch: # permite rodar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@master
        with:
          github_user_name: nathanscd
          outputs: |
            dist/contributions.svg
            dist/contributions-dark.svg?palette=github-dark&color_snake=#ff0000&color_dots=#ff0000
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
