name: Contribution grid (snake)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: nathanscd
          outputs: |
            dist/contributions.svg?color_dots=#2b0000,#5c0000,#8a0000,#ba0000,#ff2b2b
            dist/contributions-dark.svg?palette=github-dark&color_dots=#1a0000,#4d0000,#7f0000,#b30000,#ff4d4d

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
